"""Countries table

Revision ID: dc7dbef161a8
Revises: 
Create Date: 2022-08-07 18:30:29.169178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dc7dbef161a8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    countries_table = op.create_table(
        "countries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        countries_table,
        [
            {'name':'Chile'},
            {'name': 'Mexico'},
            {'name': 'Colombia'},
            {'name': 'Peru'},
        ]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("countries")
    # ### end Alembic commands ###
