"""Add active field to Workers

Revision ID: fb1ce716e13c
Revises: 93a0bca2b6d6
Create Date: 2022-08-07 20:51:56.628161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1ce716e13c'
down_revision = '93a0bca2b6d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('active', sa.Boolean(), server_default='true', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'active')
    # ### end Alembic commands ###
